#!/bin/bash

if ! [[ -e /tmp/.ran_once ]]; then
	touch /tmp/.ran_once
	chown -R 1000:100 /workspace /var/lib/php /tmp
	find /var/log -type d -exec chmod 777 {} \;
	# php-fpm config
	sed -ri \
		"s/user = (\w|\d|-)+/user = 1000/g;
		s/group = (\w|\d|-)+/group = 100/g" "/etc/php/${PHP_VERSION:0:3}/fpm/php-fpm.conf" "/etc/php/${PHP_VERSION:0:3}/fpm/pool.d/www.conf"
fi

exec "php-fpm${PHP_VERSION:0:3}" --nodaemonize
